# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: Patricio Echagüe Ballesteros
#subtitle:
subtitle: Tlf.: +34 616 693 953 - eMail: pechagueb@gmail.com

# Title attribute of HTML Page, uses 'name' from above if empty
title: Patricio Echagüe

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: One line of text describing the content of the page in less than 140 characters.
    keywords: foo, bar, baz
    crawl: index,follow

# website address when deployed, also given as canonical link
url: "https://pechagueb.github.io"

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: '/pebweb'

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge
# the GA cookies. Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip'
# below. You normally want that. https://support.google.com/analytics/answer/2763052
#ga:
ga:
    account: 'UA-120960520-1'
    cookieconsent: true
    anonymizeip: true

# Plausible.io Analytics (alternative to Google Analytics that does not need cookies -> no cookie consent required)
# A config setting is required in plausible to enable tracking of the outbound links. Details described here:
# https://plausible.io/docs/outbound-link-click-tracking
# Leave empty (just "plausible:" with subitems commented out) to disable.
#plausible:
plausible:
    domain: "https://pechagueb.github.io"


# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "images/PEB-25.jpg"
#avatar: "images/jonathan_doe.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - facebook:
      name: Facebook
      show: true
      href: https://facebook.com/patricio.echagueballesteros
      icon: fa-brands fa-facebook
  - yapadesign:
      name: YapaDesign
      show: true
      href: https://www.facebook.com/yapadesign/
      icon: fa-brands fa-facebook
  - enercan:
      name: EnerCan
      show: true
      href: https://www.facebook.com/renovablescanarias
      icon: fa-brands fa-facebook
  - youtube:
      name: Youtube
      show: true
      href: https://www.youtube.com/@patricioeb
      icon: fa-brands fa-youtube
  - linkedin:
      name: LinkedIn
      show: true
      href: https://www.linkedin.com/in/patricio-echag%C3%BCe-ballesteros-855484139/
      icon: fa-brands fa-linkedin
  - instagram:
      name: Instagram
      show: true
      href: https://www.instagram.com/patechagueb
      icon: fa-brands fa-instagram
  - flickr:
      name: Flickr
      show: true
      href: https://www.flickr.com/photos/90581146@N08/
      icon: fa-brands fa-flickr
  - github:
      name: GitHub
      show: true
      href: https://github.com/pechagueb
      icon: fa-brands fa-github
  - reddit:
      name: Reddit
      show: false
      href: https://reddit.com/user/YOUR_REDDIT_USERNAME
      icon: fa-brands fa-reddit
  - blog:
      name: Blog
      show: true
      href: https://pechagueb.blogspot.com/
      icon: fa-solid fa-book-open
  - email:
      name: Email
      show: true
      href: mailto:pechagueb@gmail.com
      icon: fa-solid fa-envelope


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:
# extra_html: >
##    Any (multiline) text containing simple HTML,
#    such as links or ... lorem ipsum.
    
extra_html: >

# Configuración del Último Post
latest_post:
  show: true
  title: "Último Post"
  image: "images/ultimo-post.jpg"
  url: "https://www.facebook.com/yapadesign"

#EOF
