color0 #4a454e
color1 #ffb4ab
color2 #d6bbfb
color3 #cec2da
color4 #f2b7c2
color5 #d6bbfb
color6 #cec2da
color7 #e7e0e8
color8 #958e99
color9 #ffb4ab
color10 #d6bbfb
color11 #cec2da
color12 #f2b7c2
color13 #d6bbfb
color14 #cec2da
color15 #e7e0e8

cursor                #e7e0e8
cursor_text_color     #151218
background            #151218
foreground            #e7e0e8
selection_foreground  #cbc4cf
selection_background  #4a454e
active_border_color   #d6bbfb
inactive_border_color #4a454e
url_color             #d6bbfb

active_tab_foreground   #3b255b
active_tab_background   #d6bbfb
inactive_tab_foreground #cbc4cf
inactive_tab_background #4a454e
cursor_trail_color      #cbc4cf
