color0 #42474e
color1 #ffb4ab
color2 #9bcbfb
color3 #b9c8da
color4 #d3bfe6
color5 #9bcbfb
color6 #b9c8da
color7 #e0e2e8
color8 #8c9198
color9 #ffb4ab
color10 #9bcbfb
color11 #b9c8da
color12 #d3bfe6
color13 #9bcbfb
color14 #b9c8da
color15 #e0e2e8

cursor                #e0e2e8
cursor_text_color     #101418
background            #101418
foreground            #e0e2e8
selection_foreground  #c2c7cf
selection_background  #42474e
active_border_color   #9bcbfb
inactive_border_color #42474e
url_color             #9bcbfb

active_tab_foreground   #003353
active_tab_background   #9bcbfb
inactive_tab_foreground #c2c7cf
inactive_tab_background #42474e
cursor_trail_color      #c2c7cf
